apiVersion: v1
kind: Namespace
metadata:
  name: tech-prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
  namespace: tech-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
      - name: python-container
        image: eldanius/python-microservice  # Usar tu imagen de Docker Hub
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        ports:
        - containerPort: 5000
        env:
        - name: NETWORK
          value: "internal prod"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: python-microservice
  namespace: tech-prod
spec:
  selector:
    app: python-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
