apiVersion: v1
kind: Service
metadata:
  name: python-microservice
  namespace: tech-prod
spec:
  type: LoadBalancer
  selector:
    app: python-microservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
